# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dldd_clogit <- function(designmat, RRs) {
    .Call(`_ameras_dldd_clogit`, designmat, RRs)
}

dldd_prophaz <- function(entry_t, exit_t, status_ord, RRs) {
    .Call(`_ameras_dldd_prophaz`, entry_t, exit_t, status_ord, RRs)
}

loglik_prophaz_rcpp <- function(exit_t, entry_t, RR_entry, RR_exit, status_ord, loglim) {
    .Call(`_ameras_loglik_prophaz_rcpp`, exit_t, entry_t, RR_entry, RR_exit, status_ord, loglim)
}

compute_ERCsum_clogit <- function(set_members, RRs, drdd, drdd2, status, Kmat) {
    .Call(`_ameras_compute_ERCsum_clogit`, set_members, RRs, drdd, drdd2, status, Kmat)
}

compute_ERCsum_prophaz <- function(entry_t, exit_t, status_ord, RRs, drdd, drdd2, Xc, Kmat_diag, dldd) {
    .Call(`_ameras_compute_ERCsum_prophaz`, entry_t, exit_t, status_ord, RRs, drdd, drdd2, Xc, Kmat_diag, dldd)
}

